global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gatekeeper'
    static_configs:
      - targets: ['gatekeeper:8000']

  - job_name: 'switch'
    static_configs:
      - targets: ['switch:8001']

  - job_name: 'labyrinth'
    static_configs:
      - targets: ['labyrinth:8002']

  - job_name: 'sentinel'
    static_configs:
      - targets: ['sentinel:8003']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
