global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gatekeeper'
    static_configs:
      - targets: ['cerberus-gatekeeper:8000']

  - job_name: 'switch'
    static_configs:
      - targets: ['cerberus-switch:8001']

  - job_name: 'labyrinth'
    static_configs:
      - targets: ['cerberus-labyrinth:8002']

  - job_name: 'sentinel'
    static_configs:
      - targets: ['cerberus-sentinel:8003']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['cerberus-redis-exporter:9121']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['cerberus-kafka-exporter:9308']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['cerberus-prometheus:9090']
