version: '3.8'

services:
  envoy-switch:
    image: envoyproxy/envoy:v1.24-latest
    ports:
      - "8081:8081"
    volumes:
      - ./switch/envoy_stub/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - switch
      - redis
      - labyrinth
    networks:
      - cerberus-net

  switch:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.switch
    ports:
      - "8001:8001"
    depends_on:
      - kafka
      - redis
      - postgres
    networks:
      - cerberus-net
    volumes:
      - ./data:/app/data
      - ./switch:/app/switch

networks:
  cerberus-net:
    driver: bridge
